defaults: &defaults
  adapter: mysql2
  username: walk_the_walk
  password: 'Hello!23'
  host: localhost

development:
  <<: *defaults
  database: walk_the_walk_development
  
test:
  <<: *defaults
  database: walk_the_walk_test

production:
  <<: *defaults
  database: walk_the_walk_production
  host: db.walkthewalkfoundation.com
